### ISSUE TITLE
hook index_batch fails on objects with no IUUID support

### ISSUE THREAD

**Issue by ewohnlich** [collective/collective.elasticsearch#24]
I'm not entirely sure what is going on in hook.py but IUUID(ob) fails on portal_setup. I don't detect any problems converting my catalog nor searching for new or converted content, but I get this error in Plone 5.0.5

`2017-02-17 16:37:26 ERROR txn.7012 Error in after commit hook exec in <collective.elasticsearch.hook.CommitHook object at 0x000000001A085898> 
Traceback (most recent call last):
  File "c:\plone5\eggs\transaction-1.1.1-py2.7.egg\transaction\_transaction.py", line 416, in _callAfterCommitHooks
    hook(status, *args, **kws)
  File "c:\plone5\eggs\collective.elasticsearch-2.0.0a2-py2.7.egg\collective\elasticsearch\hook.py", line 221, in __call__
    index_batch(self.remove, self.index, self.positions, self.es)
  File "c:\plone5\eggs\collective.elasticsearch-2.0.0a2-py2.7.egg\collective\elasticsearch\hook.py", line 91, in index_batch
    '_id': IUUID(ob)
TypeError: ('Could not adapt', <SetupTool at /Plone/portal_setup>, <InterfaceClass plone.uuid.interfaces.IUUID>)`

Obviously there's nothing I actually want to index in portal_setup anyway, but it's part of a list of ids of everything on site root. I believe you can just add a conditional "if IUUID(ob,None)" around the offending block

**Comment by ewohnlich** [comment]
Similar error when an object without an IUUID adapter ends up in "positions" for index_batch.

```
Error in after commit hook exec in <collective.elasticsearch.hook.CommitHook object at 0x7f9e85a76f90> Traceback (most recent call last):
  File "/sprj/st_zope_plone5/plone-st-03/buildouts/eggs/transaction-2.1.2-py2.7.egg/transaction/_transaction.py", line 393, in _callAfterCommitHooks
    hook(status, *args, **kws)
  File "/sprj/st_zope_plone5/plone-st-03/buildouts/eggs/collective.elasticsearch-3.0.3-py2.7.egg/collective/elasticsearch/hook.py", line 242, in __call__
    index_batch(self.remove, self.index, self.positions, self.es)
  File "/sprj/st_zope_plone5/plone-st-03/buildouts/eggs/collective.elasticsearch-3.0.3-py2.7.egg/collective/elasticsearch/hook.py", line 105, in index_batch
    '_id': IUUID(ob)
TypeError: ('Could not adapt', <WorkflowPolicyConfig at /db03/prism/analysis-and-methods/tumor-necrosis-factor-alpha-inhibitors-study/.wf_policy_config>, <InterfaceClass plone.uuid.interfaces.IUUID>)
```
In my case the object is a workflow policy config from CMFPlacefulWorkflow. This only gets its id added to the positions variable when something else in that container is moved with the "move to top/bottom" actions. Maybe this line should use the getUID function from utils instead of IUUID directly? https://github.com/collective/collective.elasticsearch/blob/master/collective/elasticsearch/hook.py#L106
