### ISSUE TITLE
Request error on search in 3.0.0

### ISSUE THREAD

**Issue by ewohnlich** [collective/collective.elasticsearch#48]
I'm getting the following on a windows build of Plone 5.0.5 with elasticsearch 6.3.1 when searching within the Related Items field.

```2019-01-28 15:46:52 WARNING elasticsearch GET http://127.0.0.1:9200/alabama-portal_catalog/portal_catalog/_search?stored_fields=path.path&size=50 [status:400 request:0.137s]
2019-01-28 15:46:52 ERROR collective.elasticsearch Error running Query: {'allowedRolesAndUsers': ['user:admin', 'Manager', 'Authenticated', 'Anonymous'], 'sort_on': u'sortable_title', 'sort_order': 'ascending', u'SearchableText': {'query': u'banana*'}}
Traceback (most recent call last):
  File "c:\plone5\src\collective.elasticsearch\collective\elasticsearch\es.py", line 298, in searchResults
    results = self.search(query)
  File "c:\plone5\src\collective.elasticsearch\collective\elasticsearch\es.py", line 183, in search
    result = ElasticResult(self, query, **query_params)
  File "c:\plone5\src\collective.elasticsearch\collective\elasticsearch\es.py", line 49, in __init__
    result = es._search(self.query, sort=self.sort, **query_params)['hits']
  File "c:\plone5\src\collective.elasticsearch\collective\elasticsearch\es.py", line 169, in _search
    **query_params)
  File "c:\plone5\eggs\elasticsearch-6.3.1-py2.7.egg\elasticsearch\client\utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "c:\plone5\eggs\elasticsearch-6.3.1-py2.7.egg\elasticsearch\client\__init__.py", line 660, in search
    doc_type, '_search'), params=params, body=body)
  File "c:\plone5\eggs\elasticsearch-6.3.1-py2.7.egg\elasticsearch\transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "c:\plone5\eggs\elasticsearch-6.3.1-py2.7.egg\elasticsearch\connection\http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "c:\plone5\eggs\elasticsearch-6.3.1-py2.7.egg\elasticsearch\connection\base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: RequestError(400, u'search_phase_execution_exception', u'Fielddata is disabled on text fields by default. Set fielddata=true on [sortable_title] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.')
```

Hopefully this error means something to you - the error log in elasticsearch is quite verbose but seems to be complaining about the same thing.

If I have the old ZCTextIndexes in place both this and the regular search work, but otherwise will not. Unsure if related: when running the Convert Catalog step it shows 7 docs (this is an out-of-the-box test site plus one page) but Rebuild Catalog always drops that to 0.

I've been using es 2 with collective.elasticsearch==2.0.5 without issue

**Comment by vangheem** [comment]
Hi @ewohnlich!

Thank you for the report. Would you be able to test adding `sortable_title` to https://github.com/collective/collective.elasticsearch/blob/master/collective/elasticsearch/indexes.py#L49 and seeing if that fixes the problem?

**Comment by ewohnlich** [comment]
Sure, this seemed to have a few effects. The search box viewlet worked as expected immediately. The related fields widget seemed to work after I did the Rebuild Catalog step (and this now displays the expected 7 docs, without having to run Convert Catalog again).

FWIW my sortable_title index is the default FieldIndex and not a KeywordIndex.

**Comment by vangheem** [comment]
Yup, it has to do with differences between ES and plone and how search works...  Things don't map over perfectly.

Would you be able to make a PR with that change?
